pub mod ipc_client;

pub use ipc_client::IpcLlmClient;

use crate::error::AvixError;
use async_trait::async_trait;
use futures::stream::BoxStream;
use serde::{Deserialize, Serialize};
use std::str::FromStr;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    EndTurn,
    ToolUse,
    MaxTokens,
    StopSequence,
}

/// A single chunk emitted during a streaming LLM completion.
///
/// The caller accumulates `TextDelta` chunks into the final response text,
/// and collects `ToolCallStart` / `ToolCallArgsDelta` / `ToolCallComplete`
/// chunks to reconstruct tool calls.  `Done` signals that the stream has
/// finished and carries final usage statistics.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum StreamChunk {
    TextDelta {
        text: String,
    },
    ToolCallStart {
        call_id: String,
        name: String,
    },
    ToolCallArgsDelta {
        call_id: String,
        args_delta: String,
    },
    ToolCallComplete {
        call_id: String,
    },
    Done {
        stop_reason: StopReason,
        input_tokens: u32,
        output_tokens: u32,
    },
}

impl FromStr for StopReason {
    type Err = AvixError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "end_turn" => Ok(Self::EndTurn),
            "tool_use" => Ok(Self::ToolUse),
            "max_tokens" => Ok(Self::MaxTokens),
            "stop_sequence" => Ok(Self::StopSequence),
            other => Err(AvixError::ConfigParse(format!(
                "unknown stop reason: {other}"
            ))),
        }
    }
}

fn default_turn_id() -> uuid::Uuid {
    uuid::Uuid::nil()
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmCompleteRequest {
    pub model: String,
    pub messages: Vec<serde_json::Value>,
    pub tools: Vec<serde_json::Value>,
    pub system: Option<String>,
    pub max_tokens: u32,
    /// Correlation ID for this LLM turn.  Generated by `RuntimeExecutor`
    /// and propagated through IPC to `llm.svc` so streaming chunks can be
    /// correlated with the turn that produced them.
    #[serde(default = "default_turn_id")]
    pub turn_id: uuid::Uuid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmCompleteResponse {
    pub content: Vec<serde_json::Value>,
    pub stop_reason: StopReason,
    pub input_tokens: u32,
    pub output_tokens: u32,
}

impl LlmCompleteResponse {
    pub fn total_tokens(&self) -> u32 {
        self.input_tokens + self.output_tokens
    }
}

#[async_trait]
pub trait LlmClient: Send + Sync {
    async fn complete(&self, req: LlmCompleteRequest) -> anyhow::Result<LlmCompleteResponse>;

    /// Stream a completion, emitting `StreamChunk`s as they arrive from the
    /// provider.  The stream ends with exactly one `StreamChunk::Done`.
    ///
    /// Default implementation returns an error — providers that support
    /// streaming must override this.
    async fn stream_complete(
        &self,
        req: LlmCompleteRequest,
    ) -> anyhow::Result<BoxStream<'static, anyhow::Result<StreamChunk>>> {
        let _ = req;
        Err(anyhow::anyhow!(
            "streaming not supported by this LLM client"
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stop_reason_serializes_as_snake_case() {
        assert_eq!(
            serde_json::to_value(StopReason::EndTurn).unwrap(),
            serde_json::json!("end_turn")
        );
        assert_eq!(
            serde_json::to_value(StopReason::ToolUse).unwrap(),
            serde_json::json!("tool_use")
        );
        assert_eq!(
            serde_json::to_value(StopReason::MaxTokens).unwrap(),
            serde_json::json!("max_tokens")
        );
        assert_eq!(
            serde_json::to_value(StopReason::StopSequence).unwrap(),
            serde_json::json!("stop_sequence")
        );
    }

    #[test]
    fn stop_reason_round_trips() {
        for variant in [
            StopReason::EndTurn,
            StopReason::ToolUse,
            StopReason::MaxTokens,
            StopReason::StopSequence,
        ] {
            let json = serde_json::to_value(&variant).unwrap();
            let back: StopReason = serde_json::from_value(json).unwrap();
            assert_eq!(variant, back);
        }
    }

    #[test]
    fn stream_chunk_serde_text_delta() {
        let chunk = StreamChunk::TextDelta {
            text: "hello".into(),
        };
        let v = serde_json::to_value(&chunk).unwrap();
        assert_eq!(v["type"], "text_delta");
        assert_eq!(v["text"], "hello");
        let back: StreamChunk = serde_json::from_value(v).unwrap();
        assert!(matches!(back, StreamChunk::TextDelta { text } if text == "hello"));
    }

    #[test]
    fn stream_chunk_serde_done() {
        let chunk = StreamChunk::Done {
            stop_reason: StopReason::EndTurn,
            input_tokens: 10,
            output_tokens: 5,
        };
        let v = serde_json::to_value(&chunk).unwrap();
        assert_eq!(v["type"], "done");
        assert_eq!(v["stop_reason"], "end_turn");
        assert_eq!(v["input_tokens"], 10);
        assert_eq!(v["output_tokens"], 5);
    }

    #[test]
    fn stream_chunk_tool_call_round_trip() {
        let start = StreamChunk::ToolCallStart {
            call_id: "c1".into(),
            name: "fs/read".into(),
        };
        let v = serde_json::to_value(&start).unwrap();
        assert_eq!(v["type"], "tool_call_start");

        let delta = StreamChunk::ToolCallArgsDelta {
            call_id: "c1".into(),
            args_delta: "{\"path\":".into(),
        };
        let v2 = serde_json::to_value(&delta).unwrap();
        assert_eq!(v2["type"], "tool_call_args_delta");

        let complete = StreamChunk::ToolCallComplete {
            call_id: "c1".into(),
        };
        let v3 = serde_json::to_value(&complete).unwrap();
        assert_eq!(v3["type"], "tool_call_complete");
    }

    #[test]
    fn llm_complete_request_turn_id_defaults_to_nil() {
        let json = serde_json::json!({
            "model": "m",
            "messages": [],
            "tools": [],
            "system": null,
            "max_tokens": 512,
        });
        let req: LlmCompleteRequest = serde_json::from_value(json).unwrap();
        assert_eq!(req.turn_id, uuid::Uuid::nil());
    }

    #[test]
    fn llm_complete_request_turn_id_round_trips() {
        let id = uuid::Uuid::new_v4();
        let req = LlmCompleteRequest {
            model: "m".into(),
            messages: vec![],
            tools: vec![],
            system: None,
            max_tokens: 512,
            turn_id: id,
        };
        let v = serde_json::to_value(&req).unwrap();
        assert_eq!(v["turn_id"], id.to_string());
        let back: LlmCompleteRequest = serde_json::from_value(v).unwrap();
        assert_eq!(back.turn_id, id);
    }

    #[test]
    fn llm_complete_request_uses_snake_case_on_wire() {
        let req = LlmCompleteRequest {
            model: "m".into(),
            messages: vec![],
            tools: vec![],
            system: None,
            max_tokens: 512,
            turn_id: uuid::Uuid::nil(),
        };
        let v = serde_json::to_value(&req).unwrap();
        assert!(
            v.get("max_tokens").is_some(),
            "expected snake_case field max_tokens"
        );
        assert!(
            v.get("maxTokens").is_none(),
            "must not produce camelCase maxTokens"
        );
    }

    #[test]
    fn llm_complete_response_uses_snake_case_on_wire() {
        let resp = LlmCompleteResponse {
            content: vec![],
            stop_reason: StopReason::EndTurn,
            input_tokens: 10,
            output_tokens: 20,
        };
        let v = serde_json::to_value(&resp).unwrap();
        assert_eq!(v["stop_reason"], "end_turn");
        assert_eq!(v["input_tokens"], 10);
        assert_eq!(v["output_tokens"], 20);
        assert!(
            v.get("stopReason").is_none(),
            "must not produce camelCase stopReason"
        );
        assert!(v.get("inputTokens").is_none());
        assert!(v.get("outputTokens").is_none());
    }

    #[test]
    fn llm_complete_response_deserializes_from_snake_case() {
        let json = serde_json::json!({
            "content": [],
            "stop_reason": "tool_use",
            "input_tokens": 5,
            "output_tokens": 15,
        });
        let resp: LlmCompleteResponse = serde_json::from_value(json).unwrap();
        assert_eq!(resp.stop_reason, StopReason::ToolUse);
        assert_eq!(resp.input_tokens, 5);
        assert_eq!(resp.output_tokens, 15);
    }
}
